<?php

// $Author: wishcraft $
//  ------------------------------------------------------------------------ //
//                XOOPS - PHP Content Management System                      //
//                    Copyright (c) 2000 XOOPS.org                           //
//                       <http://www.xoops.org/>                             //
//  ------------------------------------------------------------------------ //
//  This program is free software; you can redistribute it and/or modify     //
//  it under the terms of the GNU General Public License as published by     //
//  the Free Software Foundation; either version 2 of the License, or        //
//  (at your option) any later version.                                      //
//                                                                           //
//  You may not change or alter any portion of this comment or credits       //
//  of supporting developers from this source code or any supporting         //
//  source code which is considered copyrighted (c) material of the          //
//  original comment or credit authors.                                      //
//                                                                           //
//  This program is distributed in the hope that it will be useful,          //
//  but WITHOUT ANY WARRANTY; without even the implied warranty of           //
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            //
//  GNU General Public License for more details.                             //
//                                                                           //
//  You should have received a copy of the GNU General Public License        //
//  along with this program; if not, write to the Free Software              //
//  Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307 USA //
//  ------------------------------------------------------------------------ //
// Author: Simon Roberts (AKA wishcraft)                                     //
// URL: http://www.chronolabs.org.au                                         //
// Project: The XOOPS Project                                                //
// ------------------------------------------------------------------------- //

$modversion['name'] = _MI_FLOWPLAYER_NAME;
$modversion['version'] = 1.16;
$modversion['releasedate'] = "Monday: March 27, 2012";
$modversion['description'] = _MI_FLOWPLAYER_DESCRIPTION;
$modversion['author'] = "Wishcraft";
$modversion['credits'] = "Simon Roberts (simon@chronolabs.coop)";
$modversion['help'] = "flowplayer.html";
$modversion['license'] = "Fibredyne Software Licence";
$modversion['official'] = 0;
$modversion['module_status']  = "Stable";
$modversion['image'] = "images/flowplayer_slogo.png";
$modversion['dirname'] = _MI_FLOWPLAYER_DIRNAME;

$modversion['system_menu'] = 1;
$modversion['hasMain'] = 1;
$modversion['website'] = "www.chronolabs.coop";

$modversion['dirmoduleadmin'] = 'Frameworks/moduleclasses';
$modversion['icons16'] = 'Frameworks/moduleclasses/icons/16';
$modversion['icons32'] = 'Frameworks/moduleclasses/icons/32';

$modversion['release_info'] = "Stable 2012/03/27";
$modversion['release_file'] = XOOPS_URL."/modules/flowplayer/docs/changelog.txt";
$modversion['release_date'] = "2012/03/27";

$modversion['author_realname'] = "Simon Roberts";
$modversion['author_website_url'] = "http://www.chronolabs.coop";
$modversion['author_website_name'] = "Chronolabs Cooperative";
$modversion['author_email'] = "simon@chronolabs.coop";
$modversion['demo_site_url'] = "";
$modversion['demo_site_name'] = "";
$modversion['support_site_url'] = "";
$modversion['support_site_name'] = "Fibredyne";
$modversion['submit_bug'] = "";
$modversion['submit_feature'] = "";
$modversion['usenet_group'] = "sci.chronolabs";
$modversion['maillist_announcements'] = "";
$modversion['maillist_bugs'] = "";
$modversion['maillist_features'] = "";

// Admin things
$modversion['hasAdmin'] = 1;
$modversion['adminindex'] = "admin/index.php?op=dashboard";
$modversion['adminmenu'] = "admin/menu.php";

// Main things
$modversion['hasMain'] = 1;

$modversion['onUpdate'] = "include/update.php";
//$modversion['onInstall'] = "include/install.php";
//$modversion['onUninstall'] = "include/uninstall.php";

// Sql file (must contain sql generated by phpMyAdmin or phpPgAdmin)
// All tables should not have any prefix!
$modversion['sqlfile']['mysql'] = "sql/mysql.sql";

// Tables created by sql file (without prefix!)
$i=0;
$modversion['tables'][$i++] = "flowplayer_player";
$modversion['tables'][$i++] = "flowplayer_mimetypes";

// Blocks
$i=0;
$i++;
$modversion['blocks'][$i]['file'] = "flowplayer_block_player.php";
$modversion['blocks'][$i]['name'] = 'Video Stream' ;
$modversion['blocks'][$i]['description'] = "Shows Video Stream Block";
$modversion['blocks'][$i]['show_func'] = "b_flowplayer_block_player_show";
$modversion['blocks'][$i]['edit_func'] = "b_flowplayer_block_player_edit";
$modversion['blocks'][$i]['options'] = "|120px|85px|player_block_one";
$modversion['blocks'][$i]['template'] = "flowplayer_block_player.html" ;

// Templates
$i=0;
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index.html';
$modversion['templates'][$i]['description'] = 'Main Index for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_iframe.html';
$modversion['templates'][$i]['description'] = 'Main Index for IFrame player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_flash_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_iframe_flash_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_flash_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_block_flash_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_rtmp_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_iframe_rtmp_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_rtmp_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_block_rtmp_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_rtsp_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_iframe_rtsp_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_rtsp_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_block_rtsp_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_ios_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_iframe_ios_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_ios_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_block_ios_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_other_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_iframe_other_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_other_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_block_other_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_silverlight_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_iframe_silverlight_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_silverlight_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_block_silverlight_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_html5_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_iframe_html5_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_html5_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_block_html5_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_http_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_index_iframe_http_player.html';
$modversion['templates'][$i]['description'] = 'Main Index Error IFrame for player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_http_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_json_block_http_player.html';
$modversion['templates'][$i]['description'] = 'Main JSON Form for Flow Player Player for blocks';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_cpanel_player_edit.html';
$modversion['templates'][$i]['description'] = 'Main control Panel Edit Video';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_cpanel_player_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel Video List';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_cpanel_mimetypes_edit.html';
$modversion['templates'][$i]['description'] = 'Main control Panel Edit Mimetypes';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_cpanel_mimetypes_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel Mimetypes List';
$i++;
$modversion['templates'][$i]['file'] = 'flowplayer_cpanel_useragents_list.html';
$modversion['templates'][$i]['description'] = 'Main Control Panel User Agent List';

$i=0;
$i++;
$modversion['config'][$i]['name'] = 'salt';
$modversion['config'][$i]['title'] = "_MI_FLOWPLAYER_SALT";
$modversion['config'][$i]['description'] = "_MI_FLOWPLAYER_SALT_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'text';
mt_srand(microtime(true));
$modversion['config'][$i]['default'] = (mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250))).(mt_rand(0,4)!=2?chr(mt_rand(32,190)):chr(mt_rand(52,250)));
$modversion['config'][$i]['options'] = array();

$i++;
$modversion['config'][$i]['name'] = 'force_jquery';
$modversion['config'][$i]['title'] = "_MI_FLOWPLAYER_FORCE_JQUERY";
$modversion['config'][$i]['description'] = "_MI_FLOWPLAYER_FORCE_JQUERY_DESC";
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = true;
$modversion['config'][$i]['options'] = array();

$i++;
$modversion['config'][$i]['name'] = 'iframe';
$modversion['config'][$i]['title'] = "_MI_FLOWPLAYER_IFRAME";
$modversion['config'][$i]['description'] = "_MI_FLOWPLAYER_IFRAME_DESC";
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = false;
$modversion['config'][$i]['options'] = array();

$i++;
$modversion['config'][$i]['name'] = 'passkey_diff';
$modversion['config'][$i]['title'] = "_MI_FLOWPLAYER_PASSKEY_DIFF";
$modversion['config'][$i]['description'] = "_MI_FLOWPLAYER_PASSKEY_DIFF_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 40;
$modversion['config'][$i]['options'] = array();

$i++;
$modversion['config'][$i]['name'] = 'passkey_weight';
$modversion['config'][$i]['title'] = "_MI_FLOWPLAYER_PASSKEY_WEIGHT";
$modversion['config'][$i]['description'] = "_MI_FLOWPLAYER_PASSKEY_WEIGHT_DESC";
$modversion['config'][$i]['formtype'] = 'text';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 60;
$modversion['config'][$i]['options'] = array();

$i++;
$modversion['config'][$i]['name'] =  'rtmp_agents';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_RTMP_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_RTMP_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Chrome|Firefox|Firebird|SeaMonkey|MSIE|Navigator|Netscape|Opera|Safari|Android|Fennec';

$i++;
$modversion['config'][$i]['name'] =  'flash_agents';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_FLASH_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_FLASH_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Chrome|Firefox|Firebird|SeaMonkey|MSIE|Navigator|Netscape|Opera|Safari|Android|Fennec';

$i++;
$modversion['config'][$i]['name'] =  'ios_agents';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_IOS_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_IOS_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'iPhone|iPad|iTouch|iPod';

$i++;
$modversion['config'][$i]['name'] =  'silverlight_agents';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_SILVERLIGHT_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_SILVERLIGHT_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Media Center PC|Trident|chromeframe|Windows-Media-Player|MSIE';

$i++;
$modversion['config'][$i]['name'] =  'rtsp_agents';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_RTSP_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_RTSP_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

$i++;
$modversion['config'][$i]['name'] =  'html5_agents';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_HTML5_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_HTML5_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'Chrome|MSIE';

$i++;
$modversion['config'][$i]['name'] =  'http_agents';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_HTTP_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_HTTP_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

$i++;
$modversion['config'][$i]['name'] =  'other_agents';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_OTHER_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_OTHER_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

$i++;
$modversion['config'][$i]['name'] =  'speciala_agents';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_SPECIALA_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_SPECIALA_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

$i++;
$modversion['config'][$i]['name'] =  'specialb_agents';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_SPECIALB_USERAGENTS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_SPECIALB_USERAGENTS_DESC';
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = '';

include_once(dirname(__FILE__).'/language/'.$GLOBALS['xoopsConfig']['language'].'/modinfo.php');

$i++;
$modversion['config'][$i]['name'] =  'default_player';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_DEFAULT_PLAYER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_DEFAULT_PLAYER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'flash';
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'rtmp_player';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_RTMP_PLAYER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_RTMP_PLAYER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'rtmp';
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'flash_player';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_FLASH_PLAYER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_FLASH_PLAYER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'flash';
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'ios_player';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_IOS_PLAYER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_IOS_PLAYER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'ios';
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'siverlight_player';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_SILVERLIGHT_PLAYER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_SILVERLIGHT_PLAYER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'silverlight';
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'rtsp_player';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_RTSP_PLAYER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_RTSP_PLAYER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'rstp';
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'html5_player';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_HTML5_PLAYER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_HTML5_PLAYER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'html5';
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'http_player';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_HTTP_PLAYER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_HTTP_PLAYER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'http';
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'other_player';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_OTHER_PLAYER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_OTHER_PLAYER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'other';
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'load_flowplayer';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_LOAD_FLOWPLAYER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_LOAD_FLOWPLAYER_DESC';
$modversion['config'][$i]['formtype'] = 'select_multi';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('flash'=>'flash', 'rtmp'=>'rtmp');
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'load_videojs';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_LOAD_VIDEOJS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_LOAD_VIDEOJS_DESC';
$modversion['config'][$i]['formtype'] = 'select_multi';
$modversion['config'][$i]['valuetype'] = 'array';
$modversion['config'][$i]['default'] = array('html5'=>'html5','ios'=>'ios','http'=>'http','rtsp'=>'rtsp');
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_PLAYER_FLASH')?constant('_MI_FLOWPLAYER_PLAYER_FLASH'):'Flash Video Player') => 'flash', (defined('_MI_FLOWPLAYER_PLAYER_HTML5')?constant('_MI_FLOWPLAYER_PLAYER_HTML5'):'HTML5 Player') => 'html5', (defined('_MI_FLOWPLAYER_PLAYER_IOS')?constant('_MI_FLOWPLAYER_PLAYER_IOS'):'iOS (Apple) Player') => 'ios', (defined('_MI_FLOWPLAYER_PLAYER_RTSP')?constant('_MI_FLOWPLAYER_PLAYER_RTSP'):'RTSP Player') => 'rtsp', (defined('_MI_FLOWPLAYER_PLAYER_RTMP')?constant('_MI_FLOWPLAYER_PLAYER_RTMP'):'RTMP Player') => 'rtmp', (defined('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT')?constant('_MI_FLOWPLAYER_PLAYER_SILVERLIGHT'):'Silverlight Player') => 'silverlight', (defined('_MI_FLOWPLAYER_PLAYER_HTTP')?constant('_MI_FLOWPLAYER_PLAYER_HTTP'):'HTTP(s) Player') => 'http', (defined('_MI_FLOWPLAYER_PLAYER_OTHER')?constant('_MI_FLOWPLAYER_PLAYER_OTHER'):'Other Player') => 'other');

$i++;
$modversion['config'][$i]['name'] =  'order_rtmp';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_ORDER_RTMP';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_ORDER_RTMP_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 2;
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_ORDER_1ST')?constant('_MI_FLOWPLAYER_ORDER_1ST'):'First') => 1, (defined('_MI_FLOWPLAYER_ORDER_2ND')?constant('_MI_FLOWPLAYER_ORDER_2ND'):'Second') => 2, (defined('_MI_FLOWPLAYER_ORDER_3RD')?constant('_MI_FLOWPLAYER_ORDER_3RD'):'Third') => 3, (defined('_MI_FLOWPLAYER_ORDER_4TH')?constant('_MI_FLOWPLAYER_ORDER_4TH'):'Forth') => 4, (defined('_MI_FLOWPLAYER_ORDER_5TH')?constant('_MI_FLOWPLAYER_ORDER_5TH'):'Fifth') => 5, (defined('_MI_FLOWPLAYER_ORDER_6TH')?constant('_MI_FLOWPLAYER_ORDER_6TH'):'Sixth') => 6, (defined('_MI_FLOWPLAYER_ORDER_7TH')?constant('_MI_FLOWPLAYER_ORDER_7TH'):'Seventh') => 7, (defined('_MI_FLOWPLAYER_ORDER_8TH')?constant('_MI_FLOWPLAYER_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_flash';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_ORDER_FLASH';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_ORDER_FLASH_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 4;
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_ORDER_1ST')?constant('_MI_FLOWPLAYER_ORDER_1ST'):'First') => 1, (defined('_MI_FLOWPLAYER_ORDER_2ND')?constant('_MI_FLOWPLAYER_ORDER_2ND'):'Second') => 2, (defined('_MI_FLOWPLAYER_ORDER_3RD')?constant('_MI_FLOWPLAYER_ORDER_3RD'):'Third') => 3, (defined('_MI_FLOWPLAYER_ORDER_4TH')?constant('_MI_FLOWPLAYER_ORDER_4TH'):'Forth') => 4, (defined('_MI_FLOWPLAYER_ORDER_5TH')?constant('_MI_FLOWPLAYER_ORDER_5TH'):'Fifth') => 5, (defined('_MI_FLOWPLAYER_ORDER_6TH')?constant('_MI_FLOWPLAYER_ORDER_6TH'):'Sixth') => 6, (defined('_MI_FLOWPLAYER_ORDER_7TH')?constant('_MI_FLOWPLAYER_ORDER_7TH'):'Seventh') => 7, (defined('_MI_FLOWPLAYER_ORDER_8TH')?constant('_MI_FLOWPLAYER_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_ios';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_ORDER_IOS';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_ORDER_IOS_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_ORDER_1ST')?constant('_MI_FLOWPLAYER_ORDER_1ST'):'First') => 1, (defined('_MI_FLOWPLAYER_ORDER_2ND')?constant('_MI_FLOWPLAYER_ORDER_2ND'):'Second') => 2, (defined('_MI_FLOWPLAYER_ORDER_3RD')?constant('_MI_FLOWPLAYER_ORDER_3RD'):'Third') => 3, (defined('_MI_FLOWPLAYER_ORDER_4TH')?constant('_MI_FLOWPLAYER_ORDER_4TH'):'Forth') => 4, (defined('_MI_FLOWPLAYER_ORDER_5TH')?constant('_MI_FLOWPLAYER_ORDER_5TH'):'Fifth') => 5, (defined('_MI_FLOWPLAYER_ORDER_6TH')?constant('_MI_FLOWPLAYER_ORDER_6TH'):'Sixth') => 6, (defined('_MI_FLOWPLAYER_ORDER_7TH')?constant('_MI_FLOWPLAYER_ORDER_7TH'):'Seventh') => 7, (defined('_MI_FLOWPLAYER_ORDER_8TH')?constant('_MI_FLOWPLAYER_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_silverlight';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_ORDER_SILVERLIGHT';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_ORDER_SILVERLIGHT_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 5;
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_ORDER_1ST')?constant('_MI_FLOWPLAYER_ORDER_1ST'):'First') => 1, (defined('_MI_FLOWPLAYER_ORDER_2ND')?constant('_MI_FLOWPLAYER_ORDER_2ND'):'Second') => 2, (defined('_MI_FLOWPLAYER_ORDER_3RD')?constant('_MI_FLOWPLAYER_ORDER_3RD'):'Third') => 3, (defined('_MI_FLOWPLAYER_ORDER_4TH')?constant('_MI_FLOWPLAYER_ORDER_4TH'):'Forth') => 4, (defined('_MI_FLOWPLAYER_ORDER_5TH')?constant('_MI_FLOWPLAYER_ORDER_5TH'):'Fifth') => 5, (defined('_MI_FLOWPLAYER_ORDER_6TH')?constant('_MI_FLOWPLAYER_ORDER_6TH'):'Sixth') => 6, (defined('_MI_FLOWPLAYER_ORDER_7TH')?constant('_MI_FLOWPLAYER_ORDER_7TH'):'Seventh') => 7, (defined('_MI_FLOWPLAYER_ORDER_8TH')?constant('_MI_FLOWPLAYER_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_html5';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_ORDER_HTML5';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_ORDER_HTML5_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 3;
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_ORDER_1ST')?constant('_MI_FLOWPLAYER_ORDER_1ST'):'First') => 1, (defined('_MI_FLOWPLAYER_ORDER_2ND')?constant('_MI_FLOWPLAYER_ORDER_2ND'):'Second') => 2, (defined('_MI_FLOWPLAYER_ORDER_3RD')?constant('_MI_FLOWPLAYER_ORDER_3RD'):'Third') => 3, (defined('_MI_FLOWPLAYER_ORDER_4TH')?constant('_MI_FLOWPLAYER_ORDER_4TH'):'Forth') => 4, (defined('_MI_FLOWPLAYER_ORDER_5TH')?constant('_MI_FLOWPLAYER_ORDER_5TH'):'Fifth') => 5, (defined('_MI_FLOWPLAYER_ORDER_6TH')?constant('_MI_FLOWPLAYER_ORDER_6TH'):'Sixth') => 6, (defined('_MI_FLOWPLAYER_ORDER_7TH')?constant('_MI_FLOWPLAYER_ORDER_7TH'):'Seventh') => 7, (defined('_MI_FLOWPLAYER_ORDER_8TH')?constant('_MI_FLOWPLAYER_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_rtsp';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_ORDER_RTSP';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_ORDER_RTSP_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 6;
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_ORDER_1ST')?constant('_MI_FLOWPLAYER_ORDER_1ST'):'First') => 1, (defined('_MI_FLOWPLAYER_ORDER_2ND')?constant('_MI_FLOWPLAYER_ORDER_2ND'):'Second') => 2, (defined('_MI_FLOWPLAYER_ORDER_3RD')?constant('_MI_FLOWPLAYER_ORDER_3RD'):'Third') => 3, (defined('_MI_FLOWPLAYER_ORDER_4TH')?constant('_MI_FLOWPLAYER_ORDER_4TH'):'Forth') => 4, (defined('_MI_FLOWPLAYER_ORDER_5TH')?constant('_MI_FLOWPLAYER_ORDER_5TH'):'Fifth') => 5, (defined('_MI_FLOWPLAYER_ORDER_6TH')?constant('_MI_FLOWPLAYER_ORDER_6TH'):'Sixth') => 6, (defined('_MI_FLOWPLAYER_ORDER_7TH')?constant('_MI_FLOWPLAYER_ORDER_7TH'):'Seventh') => 7, (defined('_MI_FLOWPLAYER_ORDER_8TH')?constant('_MI_FLOWPLAYER_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_http';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_ORDER_HTTP';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_ORDER_HTTP_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 7;
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_ORDER_1ST')?constant('_MI_FLOWPLAYER_ORDER_1ST'):'First') => 1, (defined('_MI_FLOWPLAYER_ORDER_2ND')?constant('_MI_FLOWPLAYER_ORDER_2ND'):'Second') => 2, (defined('_MI_FLOWPLAYER_ORDER_3RD')?constant('_MI_FLOWPLAYER_ORDER_3RD'):'Third') => 3, (defined('_MI_FLOWPLAYER_ORDER_4TH')?constant('_MI_FLOWPLAYER_ORDER_4TH'):'Forth') => 4, (defined('_MI_FLOWPLAYER_ORDER_5TH')?constant('_MI_FLOWPLAYER_ORDER_5TH'):'Fifth') => 5, (defined('_MI_FLOWPLAYER_ORDER_6TH')?constant('_MI_FLOWPLAYER_ORDER_6TH'):'Sixth') => 6, (defined('_MI_FLOWPLAYER_ORDER_7TH')?constant('_MI_FLOWPLAYER_ORDER_7TH'):'Seventh') => 7, (defined('_MI_FLOWPLAYER_ORDER_8TH')?constant('_MI_FLOWPLAYER_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'order_other';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_ORDER_OTHER';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_ORDER_OTHER_DESC';
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 8;
$modversion['config'][$i]['options'] = array((defined('_MI_FLOWPLAYER_ORDER_1ST')?constant('_MI_FLOWPLAYER_ORDER_1ST'):'First') => 1, (defined('_MI_FLOWPLAYER_ORDER_2ND')?constant('_MI_FLOWPLAYER_ORDER_2ND'):'Second') => 2, (defined('_MI_FLOWPLAYER_ORDER_3RD')?constant('_MI_FLOWPLAYER_ORDER_3RD'):'Third') => 3, (defined('_MI_FLOWPLAYER_ORDER_4TH')?constant('_MI_FLOWPLAYER_ORDER_4TH'):'Forth') => 4, (defined('_MI_FLOWPLAYER_ORDER_5TH')?constant('_MI_FLOWPLAYER_ORDER_5TH'):'Fifth') => 5, (defined('_MI_FLOWPLAYER_ORDER_6TH')?constant('_MI_FLOWPLAYER_ORDER_6TH'):'Sixth') => 6, (defined('_MI_FLOWPLAYER_ORDER_7TH')?constant('_MI_FLOWPLAYER_ORDER_7TH'):'Seventh') => 7, (defined('_MI_FLOWPLAYER_ORDER_8TH')?constant('_MI_FLOWPLAYER_ORDER_8TH'):'Eigth') => 8);

$i++;
$modversion['config'][$i]['name'] =  'rtmp_secure';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_RTMP_PLAYER_SECURE';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_RTMP_PLAYER_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'flash_secure';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_FLASH_PLAYER_SECURE';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_FLASH_PLAYER_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'ios_secure';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_IOS_PLAYER_SECURE';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_IOS_PLAYER_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'silverlight_secure';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_SILVERLIGHT_PLAYER_SECURE';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_SILVERLIGHT_PLAYER_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'rtsp_secure';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_RTSP_PLAYER_SECURE';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_RTSP_PLAYER_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'html5_secure';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_HTML5_PLAYER_SECURE';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_HTML5_PLAYER_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'http_secure';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_HTTP_PLAYER_SECURE';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_HTTP_PLAYER_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] =  'other_secure';
$modversion['config'][$i]['title'] = '_MI_FLOWPLAYER_OTHER_PLAYER_SECURE';
$modversion['config'][$i]['description'] = '_MI_FLOWPLAYER_OTHER_PLAYER_SECURE_DESC';
$modversion['config'][$i]['formtype'] = 'yesno';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = 1;

$i++;
$modversion['config'][$i]['name'] = 'filesize_upload';
$modversion['config'][$i]['title'] = "_MI_FLOWPLAYER_FILESIZEUPLD";
$modversion['config'][$i]['description'] = "_MI_FLOWPLAYER_FILESIZEUPLD_DESC";
$modversion['config'][$i]['formtype'] = 'textbox';
$modversion['config'][$i]['valuetype'] = 'int';
$modversion['config'][$i]['default'] = '1950351';

$i++;
$modversion['config'][$i]['name'] = 'allowed_mimetype';
$modversion['config'][$i]['title'] = "_MI_FLOWPLAYER_ALLOWEDMIMETYPE";
$modversion['config'][$i]['description'] = "_MI_FLOWPLAYER_ALLOWEDMIMETYPE_DESC";
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'image/gif|image/pjpeg|image/jpeg|image/x-png|image/png';

$i++;
$modversion['config'][$i]['name'] = 'allowed_extensions';
$modversion['config'][$i]['title'] = "_MI_FLOWPLAYER_ALLOWEDEXTENSIONS";
$modversion['config'][$i]['description'] = "_MI_FLOWPLAYER_ALLOWEDEXTENSIONS_DESC";
$modversion['config'][$i]['formtype'] = 'textarea';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'gif|pjpeg|jpeg|jpg|png';

$i++;
$modversion['config'][$i]['name'] = 'upload_areas';
$modversion['config'][$i]['title'] = "_MI_FLOWPLAYER_UPLOADAREAS";
$modversion['config'][$i]['description'] = "_MI_FLOWPLAYER_UPLOADAREAS_DESC";
$modversion['config'][$i]['formtype'] = 'select';
$modversion['config'][$i]['valuetype'] = 'text';
$modversion['config'][$i]['default'] = 'uploads'.DS.'flowplayer'.DS;
$modversion['config'][$i]['options'] = array(
												'uploads'.DS => 'uploads'.DS,
												'uploads'.DS.'flowplayer'.DS => 'uploads'.DS.'flowplayer'.DS
										);

?>
